export * as path from 'https://deno.land/std@0.214.0/path/mod.ts';
export * as cookie from 'https://deno.land/std@0.214.0/http/cookie.ts';
export * as base64 from 'https://deno.land/std@0.214.0/encoding/base64.ts';
export {existsSync} from 'https://deno.land/std@0.214.0/fs/exists.ts';
export {ensureFileSync} from 'https://deno.land/std@0.214.0/fs/ensure_file.ts';
export {ensureDirSync} from 'https://deno.land/std@0.214.0/fs/ensure_dir.ts';
export {deepMerge} from 'https://deno.land/std@0.214.0/collections/deep_merge.ts';
export {serveDir} from 'https://deno.land/std@0.214.0/http/file_server.ts';
export * as velocirouter from 'https://deno.land/x/velocirouter@v0.7.1/mod.ts';
export * as svelte from 'npm:svelte@4.2.10/compiler';
export * as acorn from 'npm:acorn@8.11.3';
export {default as MurmurHash3} from 'https://deno.land/x/murmurhash@v1.0.0/mod.ts';
