export * as path from '@std/path';
export * as cookie from '@std/http/cookie';
export type {Cookie} from '@std/http/cookie';
export {encodeBase64} from '@std/encoding';
export {existsSync, ensureFileSync, ensureDirSync} from '@std/fs';
export {deepMerge} from '@std/collections/deep-merge';
export {serveDir} from '@std/http/file-server';
export {Router as VelociRouter} from '@ssr/velocirouter';
export type {Handle, Method, Platform, Router} from '@ssr/velocirouter';
export * as svelte from 'svelte/compiler';
export * as acorn from 'acorn';
