export * as path from 'https://deno.land/std@0.212.0/path/mod.ts';
export * as cookie from 'https://deno.land/std@0.212.0/http/cookie.ts';
export * as base64 from 'https://deno.land/std@0.212.0/encoding/base64.ts';
export {existsSync} from 'https://deno.land/std@0.212.0/fs/exists.ts';
export {ensureFileSync} from 'https://deno.land/std@0.212.0/fs/ensure_file.ts';
export {deepMerge} from 'https://deno.land/std@0.212.0/collections/deep_merge.ts';
export {serveFile} from 'https://deno.land/std@0.212.0/http/file_server.ts';
export * as velocirouter from 'https://deno.land/x/velocirouter@v0.5.4/mod.ts';
export * as bumble from 'https://raw.githubusercontent.com/dbushell/bumble/v0.12.1/mod.ts';
export {default as MurmurHash3} from 'https://deno.land/x/murmurhash@v1.0.0/mod.ts';
