export * as fs from 'https://deno.land/std@0.207.0/fs/mod.ts';
export * as path from 'https://deno.land/std@0.207.0/path/mod.ts';
export * as hex from 'https://deno.land/std@0.207.0/encoding/hex.ts';
export * as base64 from 'https://deno.land/std@0.207.0/encoding/base64.ts';
export {existsSync} from 'https://deno.land/std@0.207.0/fs/mod.ts';
export {deepMerge} from 'https://deno.land/std@0.207.0/collections/mod.ts';
export {serveFile} from 'https://deno.land/std@0.207.0/http/file_server.ts';
export * as velocirouter from 'https://deno.land/x/velocirouter@v0.5.0/mod.ts';
export * as bumble from 'https://raw.githubusercontent.com/dbushell/bumble/v0.7.10/mod.ts';
export * as svelte from 'npm:svelte@4.2.7/compiler';
