name: Publish and Deploy

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: publish

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      - name: Build
        run: DINOSSR_BUILD=1 DINOSSR_DEPLOY_ID=${{ github.run_id }} deno run -A docs/mod.ts

      - name: Deploy
        uses: denoland/deployctl@v1
        with:
          project: dinossr
          entrypoint: docs/mod.ts
